remote_controller:
  type: joystick
  available_mode: all
lms151:
  type: lidar
  available_mode: none
ouster:
  type: lidar
  available_mode: all
septentrio:
  type: gps
  available_mode: all
xsens:
  type: imu
  available_mode: all
