sampling_period: 10.0

# control setpoint
setpoint:
  desired_linear_speed: 0.5
  desired_lateral_deviation: 0.0
  desired_course_deviation: 0.0

# configuration of longitudinal control
longitudinal_control:
  minimal_linear_speed: 0.3

# configuration for classic and predictive lateral control laws
lateral_control:
  selected: back_stepping

  back_stepping:
    gains:
      kp: -0.5
      kd: -1.0
    maximal_omega_d: 0.5

  classic:
    gains:
      front_kd: 0.7

  predictive:
    gains:
      front_kd: 0.4
    prediction:
      horizon: 10
      a0: 0.1642
      a1: 0.1072
      b1: 1.0086
      b2: -0.2801

# other options
stop_at_the_end: false # not implemented
enable_joystick: false
autoconfigure: true
autostart: true
debug: true

# configuration for cmd_mux auto connection
cmd_output:
  message_type: romea_mobile_base_msgs/SkidSteeringCommand
  priority: -1 # if -1, disable registering to cmd_mux
  rate: 10.

debug: true
