name: "lidar"
driver:
  package: "sick_scan"
  executable: "sick_generic_caller"
  parameters:
    hostname: "192.168.1.112"
    port: 2112
configuration:
  type: sick
  model: lms151
  rate: 50
  resolution: 0.5
geometry:
  parent_link: "base_link"
  xyz: [2.02, 0.0, 0.34]
  rpy: [0.0, 0.0, 0.0]
records:
  scan: true
  cloud: false
