name: "base"
configuration:
  type: alpo
  model: fat
# control: not yet implemented
#   controller_manager:
#     update_rate: 100
#     configuration:
#       pkg: alpo_bringup
#       file: config/controller_manager.yaml
#   controller:
#     configuration:
#       pkg: alpo_bringup
#       file: config/mobile_base_controller.yaml
records:
  joint_states: true
  controller/odom: true
  controller/odometry: true
  controller/kinematic: true
simulation:
  initial_xyz: [-10.838, -1.404, 0.0]
  initial_rpy: [0.0, 0.0, -138]
